name: 'Repository Content Validator'
description: 'Validates markdown content in GitHub repositories with frontmatter and hierarchy checks'
author: 'Oleksandr Tsvirkun'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  use-check-runs:
    description: 'Enable GitHub Check Runs API (disable for local testing)'
    required: false
    default: 'false'
  auto-commit:
    description: 'Automatically commit generated metadata files'
    required: false
    default: 'false'

outputs:
  total-changes:
    description: 'Total number of files changed'
  total-files:
    description: 'Total number of JSON metadata files updated'
  validation-errors:
    description: 'Number of validation errors found'
  validation-warnings:
    description: 'Number of validation warnings found'
  conclusion:
    description: 'Overall conclusion (success or failure)'
  changes:
    description: 'JSON string with detailed change information'

runs:
  using: 'node20'
  main: 'dist/index.cjs'
